#!/usr/bin/env bash
set -euo pipefail

NMR_RETRIEVAL_PYTHON="${NMR_RETRIEVAL_PYTHON:-python}"
NMR_RETRIEVAL_CUDA_VISIBLE_DEVICES="${NMR_RETRIEVAL_CUDA_VISIBLE_DEVICES:-0}"
NMR_RETRIEVAL_SERVICE_HOST="${NMR_RETRIEVAL_SERVICE_HOST:-127.0.0.1}"
NMR_RETRIEVAL_SERVICE_PORT="${NMR_RETRIEVAL_SERVICE_PORT:-8011}"
NMR_RETRIEVAL_PRELOAD="${NMR_RETRIEVAL_PRELOAD:-1}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
NMR_CKPT_DIR="${NMR_CKPT_DIR:-$REPO_ROOT/artifacts/checkpoints}"
NMR_RUNTIME_CONFIG="${NMR_RUNTIME_CONFIG:-$REPO_ROOT/configs/runtime_assets.local.json}"
NMR_SEARCH_CKPT="${NMR_SEARCH_CKPT:-$NMR_CKPT_DIR/search.pth}"

export NMR_RETRIEVAL_PYTHON
export NMR_RETRIEVAL_CUDA_VISIBLE_DEVICES
export NMR_RETRIEVAL_SERVICE_HOST
export NMR_RETRIEVAL_SERVICE_PORT
export NMR_RETRIEVAL_PRELOAD
export NMR_RETRIEVAL_DISABLE_SERVICE=1
export NMR_RUNTIME_CONFIG
export NMR_CKPT_DIR
export NMR_SEARCH_CKPT
export CUDA_VISIBLE_DEVICES="$NMR_RETRIEVAL_CUDA_VISIBLE_DEVICES"

cd "$REPO_ROOT"
exec "$NMR_RETRIEVAL_PYTHON" Service/retrieval_service.py
