#!/usr/bin/env bash
set -euo pipefail

NMR_DENOVO_PYTHON="${NMR_DENOVO_PYTHON:-python}"
NMR_DENOVO_CUDA_VISIBLE_DEVICES="${NMR_DENOVO_CUDA_VISIBLE_DEVICES:-0}"
NMR_DENOVO_SERVICE_HOST="${NMR_DENOVO_SERVICE_HOST:-127.0.0.1}"
NMR_DENOVO_SERVICE_PORT="${NMR_DENOVO_SERVICE_PORT:-8012}"
NMR_DENOVO_PRELOAD="${NMR_DENOVO_PRELOAD:-0}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
NMR_RUNTIME_CONFIG="${NMR_RUNTIME_CONFIG:-$REPO_ROOT/configs/runtime_assets.local.json}"

export NMR_DENOVO_PYTHON
export NMR_DENOVO_CUDA_VISIBLE_DEVICES
export NMR_DENOVO_SERVICE_HOST
export NMR_DENOVO_SERVICE_PORT
export NMR_DENOVO_PRELOAD
export NMR_RUNTIME_CONFIG
export PYTHONPATH="$REPO_ROOT${PYTHONPATH:+:$PYTHONPATH}"
export CUDA_VISIBLE_DEVICES="$NMR_DENOVO_CUDA_VISIBLE_DEVICES"

cd "$REPO_ROOT"
exec "$NMR_DENOVO_PYTHON" Service/denovo_service.py
